-- SQL_4: VISAS PART 2 (Family Visas)
-- Run this fourth

INSERT INTO public.visas (subclass, name, country, category, is_active, cost_aud, processing_time_range, duration, key_requirements, official_url) VALUES
('309', 'Partner (Provisional)', 'Australia', 'family', true, '$8,085', '12-18 months', '2 years', 'Genuine relationship, Sponsor is Australian PR/citizen', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/partner-provisional-309'),
('100', 'Partner', 'Australia', 'family', true, '$1,435', 'With 309 grant', 'Permanent', 'Hold 309 for 2 years, Relationship continues', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/partner-100'),
('820', 'Partner (Temporary)', 'Australia', 'family', true, '$8,085', '12-18 months', '2 years', 'Genuine relationship, In Australia', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/partner-temporary-820'),
('801', 'Partner (Permanent)', 'Australia', 'family', true, '$1,435', 'With 820 grant', 'Permanent', 'Hold 820 for 2 years, Relationship continues', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/partner-permanent-801'),
('300', 'Prospective Marriage', 'Australia', 'family', true, '$8,085', '12-18 months', '9 months', 'Engaged to Australian, Met in person, Intent to marry', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/prospective-marriage-300'),
('101', 'Child', 'Australia', 'family', true, '$3,055', '12-18 months', 'Permanent', 'Parent is Australian PR/citizen, Under 18 or dependent', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/child-101'),
('802', 'Child (Onshore)', 'Australia', 'family', true, '$3,055', '12-18 months', 'Permanent', 'Parent is Australian PR/citizen, In Australia', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/child-onshore-802'),
('143', 'Contributory Parent', 'Australia', 'family', true, '$47,755', '5-6 years', 'Permanent', 'Balance of family test, Assurance of support, Health check', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/contributory-parent-143'),
('173', 'Contributory Parent (Temporary)', 'Australia', 'family', true, '$29,130', '2-4 years', '2 years', 'Temporary parent visa, Balance of family test', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/contributory-parent-temporary-173'),
('103', 'Parent', 'Australia', 'family', true, '$6,985', '30+ years', 'Permanent', 'Balance of family test, Assurance of support, Very long queue', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/parent-103'),
('804', 'Aged Parent', 'Australia', 'family', true, '$4,225', '30+ years', 'Permanent', 'Pension age, Long queue', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/aged-parent-804'),
('864', 'Contributory Aged Parent', 'Australia', 'family', true, '$47,755', '5-6 years', 'Permanent', 'Pension age, Fast track with higher fee', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/contributory-aged-parent-864'),
('884', 'Contributory Aged Parent (Temporary)', 'Australia', 'family', true, '$29,130', '2-4 years', '2 years', 'Temporary aged parent visa', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/contributory-aged-parent-temporary-884'),
('114', 'Aged Parent (Residence)', 'Australia', 'family', true, '$4,225', '30+ years', 'Permanent', 'Pension age, Balance of family test', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/aged-parent-residence-114'),
('838', 'Aged Dependent Relative', 'Australia', 'family', true, '$4,225', '30+ years', 'Permanent', 'Single, Dependent on Australian relative, Pension age', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/aged-dependent-relative-838'),
('836', 'Carer', 'Australia', 'family', true, '$2,055', '4-5 years', 'Permanent', 'Relative needs care, Willing to provide care', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/carer-836'),
('837', 'Orphan Relative', 'Australia', 'family', true, '$1,870', '12-18 months', 'Permanent', 'Under 18, Parent deceased, Australian relative', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/orphan-relative-837'),
('117', 'Orphan Relative (Offshore)', 'Australia', 'family', true, '$1,870', '12-18 months', 'Permanent', 'Under 18, Outside Australia, Parent deceased', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/orphan-relative-offshore-117'),
('115', 'Remaining Relative', 'Australia', 'family', true, '$4,350', '30+ years', 'Permanent', 'Remaining relative of Australian citizen/PR', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/remaining-relative-115'),
('835', 'Remaining Relative (Onshore)', 'Australia', 'family', true, '$4,350', '30+ years', 'Permanent', 'Remaining relative, In Australia', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/remaining-relative-onshore-835'),
('102', 'Adoption', 'Australia', 'family', true, '$3,055', '12-18 months', 'Permanent', 'Adopted by Australian citizen/PR, Under 18', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/adoption-102'),
('461', 'New Zealand Citizen Family Relationship', 'Australia', 'family', true, '$425', '12-18 months', '5 years', 'Family member of NZ citizen (444 holder)', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/new-zealand-citizen-family-relationship-461'),
('942', 'Sponsored Parent (Temporary)', 'Australia', 'family', true, '$1,145', '3-6 months', '3-5 years', 'Parent of Australian citizen/PR, Balance of family test waived', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/sponsored-parent-temporary-942'),
('870', 'Sponsored Parent (Temporary)', 'Australia', 'family', true, '$1,145', '3-6 months', '3-5 years', 'Temporary parent visa, New application', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/sponsored-parent-temporary-870'),
('679', 'Sponsored Family Visitor', 'Australia', 'visitor', true, '$145', '1-3 months', '12 months', 'Family sponsorship, Genuine visitor', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/sponsored-family-visitor-679'),
('417', 'Working Holiday', 'Australia', 'visitor', true, '$635', '1-2 weeks', '12 months', 'Age 18-30, Eligible passport, $5,000 funds', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/working-holiday-417'),
('462', 'Work and Holiday', 'Australia', 'visitor', true, '$635', '1-2 weeks', '12 months', 'Age 18-30, Eligible passport, $5,000 funds', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-and-holiday-462'),
('771', 'Transit', 'Australia', 'visitor', true, 'Free', 'Instant', '72 hours', 'Passing through Australia, Maximum 72 hours', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/transit-771'),
('988', 'Maritime Crew', 'Australia', 'visitor', true, 'Free', 'Instant', '30 days', 'Maritime crew, Sea-based work', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/maritime-crew-988'),
('128', 'Crew Travel Authority', 'Australia', 'visitor', true, 'Free', 'Instant', '72 hours', 'Air/sea crew, Short stopover', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/crew-travel-authority-128'),
('138', 'Medical Treatment Visa', 'Australia', 'visitor', true, 'Variable', '1-4 weeks', 'Variable', 'Medical treatment in Australia', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/medical-treatment-138'),
('602', 'Medical Treatment', 'Australia', 'visitor', true, 'Free', 'Varies', 'Varies', 'Medical treatment in Australia', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/medical-treatment-602'),
('445', 'Dependent Child', 'Australia', 'family', true, '$2,935', 'Varies', 'Temporary', 'Dependent child of temporary visa holder', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/dependent-child-445')
ON CONFLICT (subclass) DO NOTHING;

SELECT 'Total visas after Part 2: ' || COUNT(*)::text FROM public.visas;
