-- SQL_3: VISAS PART 1 (Work Visas - 33 visas)
-- Run this third

DELETE FROM public.visas;

INSERT INTO public.visas (subclass, name, country, category, is_active, cost_aud, processing_time_range, duration, key_requirements, official_url) VALUES
('189', 'Skilled Independent', 'Australia', 'work', true, '$4,640', '8-12 months', 'Permanent', 'Points test 65+, Skills assessment, Competent English', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189'),
('190', 'Skilled Nominated', 'Australia', 'work', true, '$4,640', '8-12 months', 'Permanent', 'State nomination, Points test 65+, Skills assessment', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-nominated-190'),
('491', 'Skilled Work Regional (Provisional)', 'Australia', 'work', true, '$4,640', '8-12 months', '5 years', 'State/family nomination, Regional work requirement', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-work-regional-491'),
('482', 'Temporary Skill Shortage', 'Australia', 'work', true, '$1,455', '1-3 months', '2-4 years', 'Employer sponsorship, Skills assessment, 2 years experience', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-skill-shortage-482'),
('186', 'Employer Nomination Scheme', 'Australia', 'work', true, '$4,640', '6-11 months', 'Permanent', 'Employer nomination, 3 years experience, Skills assessment', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/employer-nomination-scheme-186'),
('494', 'Skilled Employer Sponsored Regional', 'Australia', 'work', true, '$4,640', '6-9 months', '5 years', 'Regional employer sponsorship, Skills assessment', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-employer-sponsored-regional-494'),
('476', 'Skilled Recognised Graduate', 'Australia', 'work', true, '$465', '7-9 months', '18 months', 'Recent engineering degree from specified institutions', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-recognised-graduate-476'),
('887', 'Skilled Regional (Permanent)', 'Australia', 'work', true, '$425', '12-15 months', 'Permanent', 'Live in regional area 2+ years, Work 1+ year', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-regional-887'),
('191', 'Skilled Regional (Permanent)', 'Australia', 'work', true, '$465', 'Not specified', 'Permanent', 'Hold 491/494 3+ years, Meet income requirement', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-regional-permanent-191'),
('407', 'Training', 'Australia', 'work', true, '$405', '4-6 months', '2 years', 'Nomination from approved organisation, Genuine training need', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/training-407'),
('408', 'Temporary Activity', 'Australia', 'work', true, '$310', '1-4 months', 'Up to 2 years', 'Specific activity: Entertainment, Research, Sport, etc.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-activity-408'),
('403', 'Temporary Work (International Relations)', 'Australia', 'work', true, '$405', '1-4 months', 'Up to 4 years', 'Government agreement, Foreign government representative', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-work-international-relations-403'),
('400', 'Temporary Work (Short Stay Specialist)', 'Australia', 'work', true, '$405', '1-4 months', 'Up to 6 months', 'Highly specialised work, Non-ongoing role', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-work-short-stay-specialist-400'),
('416', 'Special Program', 'Australia', 'work', true, '$310', '1-3 months', 'Up to 1 year', 'Youth exchange, Cultural enrichment programs', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/special-program-416'),
('418', 'Educational', 'Australia', 'work', true, '$310', '1-3 months', 'Up to 2 years', 'Teachers and educators', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/educational-418'),
('420', 'Temporary Work (Religious)', 'Australia', 'work', true, '$310', '1-3 months', 'Up to 2 years', 'Religious workers', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-work-religious-420'),
('422', 'Medical Practitioner', 'Australia', 'work', true, '$310', '1-3 months', 'Up to 4 years', 'Medical professionals, Doctors', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/medical-practitioner-422'),
('428', 'Religious Worker', 'Australia', 'work', true, '$310', '1-3 months', 'Up to 2 years', 'Religious workers, Ministers', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/religious-worker-428'),
('444', 'Special Category (New Zealand Citizen)', 'Australia', 'work', true, 'Free', 'Instant', 'Indefinite', 'New Zealand citizen, Special category visa on arrival', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/special-category-444'),
('858', 'Global Talent (Permanent)', 'Australia', 'work', true, '$4,110', '1-3 months', 'Permanent', 'High income threshold OR Exceptional talent in target sector', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/global-talent-858'),
('124', 'Distinguished Talent', 'Australia', 'work', true, '$4,110', '12-18 months', 'Permanent', 'Internationally recognised record of exceptional achievement', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/distinguished-talent-124'),
('188', 'Business Innovation and Investment (Provisional)', 'Australia', 'business', true, '$9,455', '12-24 months', '5 years', 'Business ownership OR Investment $2.5M+ OR $5M+ significant investor', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/business-innovation-and-investment-188'),
('888', 'Business Innovation and Investment (Permanent)', 'Australia', 'business', true, '$3,490', 'With 188 conditions', 'Permanent', 'Meet 188 stream requirements, Business/Investment activity', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/business-innovation-and-investment-permanent-888'),
('132', 'Business Talent (Permanent)', 'Australia', 'business', false, 'N/A', 'N/A', 'Closed', 'Replaced by 188/888', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/business-talent-132'),
('890', 'Business Owner (Residence)', 'Australia', 'business', false, 'N/A', 'N/A', 'Closed', 'Replaced by 188/888', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/business-owner-890'),
('126', 'Domestic Worker - Diplomat', 'Australia', 'work', true, 'Variable', '2-4 weeks', 'Up to 5 years', 'Diplomat household staff', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/domestic-worker-diplomat-126'),
('411', 'Exchange', 'Australia', 'work', true, '$310', '1-4 months', 'Up to 2 years', 'Exchange programs', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/exchange-411'),
('415', 'Foreign Government Agency', 'Australia', 'work', true, '$310', '1-3 months', 'Up to 4 years', 'Foreign government workers', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/foreign-government-agency-415'),
('500', 'Student', 'Australia', 'student', true, '$710', '1-3 months', 'Course duration', 'Enrollment in CRICOS course, Financial capacity, English proficiency', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500'),
('485', 'Temporary Graduate', 'Australia', 'student', true, '$1,895', '2-4 months', '2-4 years', 'Recent Australian qualification, English proficiency', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-graduate-485'),
('590', 'Student Guardian', 'Australia', 'student', true, '$710', '1-3 months', 'Course duration', 'Guardian of student under 18, Financial capacity', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-guardian-590'),
('600', 'Visitor', 'Australia', 'visitor', true, '$190', '20-30 days', '3-12 months', 'Genuine temporary visitor, Financial capacity', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/visitor-600'),
('601', 'Electronic Travel Authority', 'Australia', 'visitor', true, '$20', 'Instant', '12 months', 'Eligible passport, No criminal record, Business/tourism', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/electronic-travel-authority-601'),
('651', 'eVisitor', 'Australia', 'visitor', true, 'Free', 'Instant', '3 months', 'Eligible European passport, Genuine visitor', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/evisitor-651')
ON CONFLICT (subclass) DO NOTHING;

SELECT 'Part 1 visas inserted: ' || COUNT(*)::text FROM public.visas;
