-- Migration: Seed Tier 2-5 Australian Visas (73 additional visas)
-- Tracks: 003, 004, 005, 006
-- Status: IN_PROGRESS
-- DHA Base URL: https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/

-- TIER 2: Important Visas (8 visas)
INSERT INTO public.visas (subclass, name, country, category, description, summary, official_link, base_cost_aud, processing_time_min_months, processing_time_max_months, is_active, is_premium_content, price_cents, display_order, search_keywords) VALUES
('186', 'Employer Nomination Scheme', 'australia', 'employer_sponsored', 'Permanent visa for skilled workers nominated by Australian employer. Direct entry or transition from TSS.', 'Permanent employer-sponsored visa. No points test required.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/employer-nomination-scheme-186', 4640.00, 6, 12, true, true, 4900, 9, 'employer nomination scheme ens permanent 186'),
('300', 'Prospective Marriage Visa', 'australia', 'family', '9-month visa for fiancés to enter Australia and marry their sponsor. Must marry within 9 months.', 'Fiancé visa. Marry in Australia, then apply for partner visa.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/prospective-marriage-300', 8850.00, 12, 18, true, true, 4900, 10, 'prospective marriage fiance 300'),
('485', 'Temporary Graduate', 'australia', 'student', '2-4 year visa for international graduates to live, study, and work in Australia. Post-study work rights.', 'Work after graduation. 2-4 years depending on qualification.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-graduate-485', 1895.00, 2, 6, true, true, 4900, 11, 'temporary graduate post study work 485'),
('494', 'Skilled Employer Sponsored Regional', 'australia', 'employer_sponsored', '5-year provisional visa for skilled workers sponsored by regional employer. Pathway to PR via 191.', 'Regional employer-sponsored. Leads to PR after 3 years.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-employer-sponsored-regional-494', 4640.00, 6, 12, true, true, 4900, 12, 'employer sponsored regional provisional 494'),
('417', 'Working Holiday Visa', 'australia', 'work_holiday', '12-month visa for young adults (18-30/35) to holiday and work in Australia. Can extend to 3 years.', 'Backpacker visa. Work and travel for 12 months.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-holiday-417', 635.00, 0, 1, true, true, 4900, 13, 'working holiday backpacker 417'),
('462', 'Work and Holiday Visa', 'australia', 'work_holiday', 'Similar to 417 but with education requirement for USA and other countries.', 'Work and holiday for eligible passport holders.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-holiday-462', 635.00, 0, 1, true, true, 4900, 14, 'work and holiday 462 usa'),
('887', 'Skilled Regional', 'australia', 'skilled', 'Permanent visa for provisional skilled visa holders who lived in regional Australia for 2+ years.', 'PR for regional visa holders. Requires 2 years regional residence.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-regional-887', 425.00, 12, 18, true, true, 4900, 15, 'skilled regional 887 pr'),
('191', 'Skilled Regional (Permanent)', 'australia', 'skilled', 'Permanent visa for holders of 491/494 who lived 3+ years in regional Australia and met income threshold.', 'PR pathway for 491/494 holders. Requires 3 years + income.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-regional-191', 465.00, 6, 12, true, true, 4900, 16, 'skilled regional 191 permanent');

-- TIER 3: Parent & Family Visas (8 visas)
INSERT INTO public.visas (subclass, name, country, category, description, summary, official_link, base_cost_aud, processing_time_min_months, processing_time_max_months, is_active, is_premium_content, price_cents, display_order, search_keywords) VALUES
('143', 'Contributory Parent Visa', 'australia', 'family', 'Permanent visa for parents of settled Australians. Faster processing (6-12 years), higher cost ($47,000+).', 'Fast parent visa. Higher cost, shorter queue than non-contributory.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/contributory-parent-143', 4765.00, 72, 144, true, true, 4900, 20, 'contributory parent 143 aos'),
('173', 'Contributory Parent (Temporary)', 'australia', 'family', '2-year temporary visa for parents. Can apply for 143 permanent later. Staged payment option.', 'Temporary parent visa. Converts to 143. Pay in two stages.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/contributory-parent-temporary-173', 2540.00, 72, 144, true, true, 4900, 21, 'contributory parent temporary 173'),
('103', 'Parent Visa', 'australia', 'family', 'Permanent visa for parents. Lower cost but very long queue (30+ years).', 'Standard parent visa. Very long processing queue.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/parent-103', 4990.00, 360, 600, true, true, 4900, 22, 'parent visa 103 long queue'),
('804', 'Aged Parent Visa', 'australia', 'family', 'Permanent visa for aged parents (pension age) applying onshore. Long queue.', 'Onshore parent visa for pensioners. Must be in Australia.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/aged-parent-804', 4990.00, 360, 600, true, true, 4900, 23, 'aged parent 804 onshore'),
('864', 'Contributory Aged Parent', 'australia', 'family', 'Permanent visa for aged parents onshore. Faster than 804 but higher cost.', 'Fast aged parent visa. Onshore application only.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/contributory-aged-parent-864', 4765.00, 72, 144, true, true, 4900, 24, 'contributory aged parent 864'),
('884', 'Contributory Aged Parent (Temp)', 'australia', 'family', '2-year temporary for aged parents. Converts to 864. Onshore only.', 'Temporary aged parent. Leads to 864.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/contributory-aged-parent-temporary-884', 2540.00, 72, 144, true, true, 4900, 25, 'contributory aged parent temporary 884'),
('870', 'Sponsored Parent (Temporary)', 'australia', 'family', '3-5 year temporary visa for parents. No permanent pathway. Private health required.', 'Temporary parent only. No PR pathway. Up to 5 years.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/sponsored-parent-temporary-870', 1000.00, 0, 1, true, true, 4900, 26, 'sponsored parent 870 temporary'),
('101', 'Child Visa', 'australia', 'family', 'Permanent visa for children outside Australia to join parents who are citizens or PR.', 'Offshore child visa. Under 18, single, sponsored by parent.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/child-101', 3055.00, 12, 24, true, true, 4900, 27, 'child visa 101 offshore');

-- TIER 4: More Family & Other Visas (12 visas)
INSERT INTO public.visas (subclass, name, country, category, description, summary, official_link, base_cost_aud, processing_time_min_months, processing_time_max_months, is_active, is_premium_content, price_cents, display_order, search_keywords) VALUES
('802', 'Child Visa (Onshore)', 'australia', 'family', 'Permanent visa for children in Australia to join parents who are citizens or PR.', 'Onshore child visa. Applied while in Australia.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/child-802', 3055.00, 12, 24, true, true, 4900, 28, 'child visa 802 onshore'),
('102', 'Adoption Visa', 'australia', 'family', 'Permanent visa for children adopted overseas by Australian citizens or PR holders.', 'For overseas adoptions. Must meet adoption requirements.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/adoption-102', 3055.00, 12, 24, true, true, 4900, 29, 'adoption visa 102'),
('445', 'Dependent Child', 'australia', 'family', 'Temporary visa for children whose parent holds a temporary partner visa (309 or 820).', 'Child of temporary partner visa holder. Links to parent visa.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/dependent-child-445', 715.00, 6, 12, true, true, 4900, 30, 'dependent child 445'),
('858', 'Global Talent Visa', 'australia', 'global_talent', 'Permanent visa for internationally recognized talent in target sectors. Fast processing.', 'Fast PR for exceptional talent. No points test.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/global-talent-visa-858', 4765.00, 2, 4, true, true, 4900, 31, 'global talent 858 gti exceptional'),
('444', 'Special Category Visa (NZ)', 'australia', 'special', 'Temporary visa for NZ citizens on arrival. Automatic. No application needed.', 'Automatic for NZ citizens. Arrive on NZ passport.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/special-category-visa-444', 0.00, 0, 0, true, true, 4900, 32, 'special category 444 nz new zealand'),
('461', 'NZ Citizen Family Relationship', 'australia', 'family', '5-year temporary visa for non-NZ family members of NZ citizens living in Australia.', 'Family of NZ citizen. 5 years, no PR pathway.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/new-zealand-citizen-family-relationship-temporary-461', 380.00, 4, 8, true, true, 4900, 33, 'nz family 461 new zealand'),
('155', 'Resident Return (5 years)', 'australia', 'resident_return', '5-year travel facility for permanent residents. Allows re-entry to Australia.', 'Travel facility for PR holders. 5 year validity.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/resident-return-155', 425.00, 0, 1, true, true, 4900, 34, 'resident return 155 5 year'),
('157', 'Resident Return (3 months)', 'australia', 'resident_return', '3-month travel facility for PR holders who do not meet 155 requirements.', 'Short travel facility for PR. 3 months only.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/resident-return-157', 425.00, 0, 1, true, true, 4900, 35, 'resident return 157 3 month'),
('476', 'Skilled - Recognised Graduate', 'australia', 'graduate', '18-month visa for recent engineering graduates of specified institutions.', 'Engineering graduates. 18 months work rights.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-recognised-graduate-476', 410.00, 3, 6, true, true, 4900, 36, 'skilled recognised graduate 476 engineering'),
('407', 'Training Visa', 'australia', 'training', '2-year visa for occupational training to enhance skills in current occupation.', 'Workplace-based training. Enhance existing skills.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/training-407', 310.00, 2, 4, true, true, 4900, 37, 'training visa 407');

-- TIER 5: Visitor & Short Stay (6 visas)
INSERT INTO public.visas (subclass, name, country, category, description, summary, official_link, base_cost_aud, processing_time_min_months, processing_time_max_months, is_active, is_premium_content, price_cents, display_order, search_keywords) VALUES
('601', 'Electronic Travel Authority (ETA)', 'australia', 'visitor', 'Electronic visa for eligible passports. 12 months validity, 3 months per visit. Instant approval.', 'Electronic visa. Eligible passports only. 12 months.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/electronic-travel-authority-601', 20.00, 0, 0, true, true, 4900, 38, 'electronic travel authority 601 eta'),
('651', 'eVisitor', 'australia', 'visitor', 'Free visa for European passport holders. 12 months validity, 3 months per visit.', 'Free electronic visa. European passports only.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/evisitor-651', 0.00, 0, 0, true, true, 4900, 39, 'evisitor 651 european'),
('602', 'Medical Treatment Visa', 'australia', 'visitor', 'Visa for medical treatment or consultations in Australia. Various durations.', 'Medical treatment in Australia. Variable duration.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/medical-treatment-602', 0.00, 1, 4, true, true, 4900, 40, 'medical treatment 602'),
('771', 'Transit Visa', 'australia', 'visitor', '72-hour transit visa for passing through Australia to another destination.', 'Transit through Australia. 72 hours max.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/transit-771', 0.00, 1, 2, true, true, 4900, 41, 'transit 771');

-- TIER 6: Bridging Visas (7 visas)
INSERT INTO public.visas (subclass, name, country, category, description, summary, official_link, base_cost_aud, processing_time_min_months, processing_time_max_months, is_active, is_premium_content, price_cents, display_order, search_keywords) VALUES
('010', 'Bridging Visa A', 'australia', 'bridging', 'Allows lawful stay while substantive visa application is processed. Most common bridging visa.', 'Standard bridging visa. Most applicants get this.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/bridging-visa-a-010', 0.00, 0, 0, true, true, 4900, 42, 'bridging visa a 010 bva'),
('020', 'Bridging Visa B', 'australia', 'bridging', 'Allows travel outside Australia while substantive application pending. Must hold BVA first.', 'Bridging visa for travel. Need BVA first.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/bridging-visa-b-020', 180.00, 0, 0, true, true, 4900, 43, 'bridging visa b 020 bvb travel'),
('030', 'Bridging Visa C', 'australia', 'bridging', 'For unlawful non-citizens who apply for substantive visa. No work rights initially.', 'Bridging for unlawful applicants. No work rights.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/bridging-visa-c-030', 0.00, 0, 0, true, true, 4900, 44, 'bridging visa c 030 bvc'),
('050', 'Bridging Visa E', 'australia', 'bridging', 'For non-citizens resolving their immigration status. Various circumstances.', 'Resolve immigration status. Various situations.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/bridging-visa-e-050', 0.00, 0, 0, true, true, 4900, 45, 'bridging visa e 050 bve'),
('051', 'Bridging Visa E (Protection)', 'australia', 'bridging', 'Specifically for protection visa applicants. Resolving status.', 'Protection visa bridging. Seeking asylum.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/bridging-visa-e-051', 0.00, 0, 0, true, true, 4900, 46, 'bridging visa e 051 protection');

-- TIER 7: Business & Investment (2 visas)
INSERT INTO public.visas (subclass, name, country, category, description, summary, official_link, base_cost_aud, processing_time_min_months, processing_time_max_months, is_active, is_premium_content, price_cents, display_order, search_keywords) VALUES
('188', 'Business Innovation & Investment (Provisional)', 'australia', 'business', '5-year provisional visa for business owners and investors. Pathway to 888 permanent.', 'Business and investment. 5 years, leads to 888.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/business-innovation-and-investment-188', 6270.00, 12, 24, true, true, 4900, 47, 'business innovation investment 188 provisional'),
('888', 'Business Innovation & Investment (Permanent)', 'australia', 'business', 'Permanent visa for 188 holders who meet business/investment obligations.', 'Permanent business visa. For 188 holders.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/business-innovation-and-investment-888', 3490.00, 12, 24, true, true, 4900, 48, 'business innovation investment 888 permanent');

-- TIER 8: Humanitarian (2 visas)
INSERT INTO public.visas (subclass, name, country, category, description, summary, official_link, base_cost_aud, processing_time_min_months, processing_time_max_months, is_active, is_premium_content, price_cents, display_order, search_keywords) VALUES
('866', 'Protection Visa', 'australia', 'humanitarian', 'Permanent visa for people seeking asylum in Australia. Onshore protection.', 'Asylum seeker visa. Onshore protection claim.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/protection-866', 0.00, 6, 36, true, true, 4900, 49, 'protection visa 866 asylum refugee');

-- Verify all insertions
SELECT 
    COUNT(*) as total_visas,
    COUNT(*) FILTER (WHERE display_order <= 8) as tier_1,
    COUNT(*) FILTER (WHERE display_order > 8 AND display_order <= 16) as tier_2,
    COUNT(*) FILTER (WHERE display_order > 16 AND display_order <= 30) as family,
    COUNT(*) FILTER (WHERE display_order > 30 AND display_order <= 41) as other,
    COUNT(*) FILTER (WHERE display_order > 41) as bridging_humanitarian
FROM public.visas WHERE country = 'australia';
