-- Migration: Seed Tier 1 Australian Visas (8 high-volume visas)
-- Track: 002
-- Status: IN_PROGRESS
-- DHA Base URL: https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/

-- Insert 8 Tier 1 MVP visas
INSERT INTO public.visas (
    subclass, 
    name, 
    country, 
    category, 
    description, 
    summary,
    official_link, 
    base_cost_aud, 
    processing_time_min_months, 
    processing_time_max_months,
    is_active,
    is_premium_content,
    price_cents,
    display_order,
    search_keywords
) VALUES 
(
    '189',
    'Skilled Independent Visa',
    'australia',
    'skilled',
    'Permanent visa for invited workers with skills Australia needs. Live and work anywhere permanently without sponsorship.',
    'Points-tested permanent visa for skilled workers. No sponsorship required.',
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189',
    4640.00,
    8,
    18,
    true,
    true,
    4900,
    1,
    'skilled independent points migration permanent 189 work live anywhere mltssl'
),
(
    '190',
    'Skilled Nominated Visa',
    'australia',
    'skilled',
    'Permanent visa for skilled workers nominated by an Australian state or territory government.',
    'State-nominated permanent visa. Extra 5 points for state nomination.',
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-nominated-190',
    4640.00,
    9,
    19,
    true,
    true,
    4900,
    2,
    'skilled nominated state sponsored migration permanent 190'
),
(
    '491',
    'Skilled Work Regional (Provisional)',
    'australia',
    'skilled',
    '5-year provisional visa for skilled workers to live and work in regional Australia. Pathway to permanent residence via subclass 191.',
    'Provisional visa for regional areas. Leads to PR after 3 years.',
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-work-regional-491',
    4640.00,
    12,
    25,
    true,
    true,
    4900,
    3,
    'skilled regional provisional points migration 491 regional area'
),
(
    '820/801',
    'Partner Visa (Onshore)',
    'australia',
    'family',
    'Combined temporary (820) and permanent (801) visa for partners of Australian citizens, permanent residents, or eligible NZ citizens. Applied in Australia.',
    'Onshore partner visa. Combined temporary and permanent pathway.',
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/partner-onshore',
    8850.00,
    18,
    30,
    true,
    true,
    4900,
    4,
    'partner spouse wife husband de facto relationship 820 801 permanent onshore'
),
(
    '309/100',
    'Partner Visa (Offshore)',
    'australia',
    'family',
    'Combined provisional (309) and permanent (100) visa for partners applied outside Australia.',
    'Offshore partner visa. Applied outside Australia, grants PR on arrival.',
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/partner-provisional-309',
    8850.00,
    15,
    26,
    true,
    true,
    4900,
    5,
    'partner spouse offshore 309 100 provisional permanent relationship'
),
(
    '500',
    'Student Visa',
    'australia',
    'student',
    'Full-time study visa for international students at Australian institutions. Work rights included.',
    'Study at Australian universities, colleges, or schools. Work up to 48hrs/fortnight.',
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500',
    710.00,
    1,
    4,
    true,
    true,
    4900,
    6,
    'student study education university college vocational school 500 coe'
),
(
    '600',
    'Visitor Visa',
    'australia',
    'visitor',
    'Temporary visa for tourism, visiting family, or business visits. No work allowed.',
    'Visit Australia for tourism or business. 3, 6, or 12 month stays.',
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/visitor-600',
    195.00,
    0,
    1,
    true,
    true,
    4900,
    7,
    'visitor tourist tourism holiday travel business 600'
),
(
    '482',
    'Temporary Skill Shortage (TSS)',
    'australia',
    'employer_sponsored',
    'Temporary visa for skilled workers sponsored by approved employers. 1-4 year duration. Pathway to PR for some occupations.',
    'Employer-sponsored work visa. Medium-term stream can lead to PR.',
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-skill-shortage-482',
    1490.00,
    0,
    2,
    true,
    true,
    4900,
    8,
    'temporary skill shortage tss employer sponsored work visa 482'
);

-- Verify insertion
SELECT COUNT(*) as tier_1_visas FROM public.visas WHERE display_order <= 8;
