-- ============================================================================
-- COMPREHENSIVE DATA SEEDING MIGRATION
-- VisaBuild - Full Dataset for Development & Testing
-- Created: 2026-02-22
-- ============================================================================

-- Enable extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================================
-- PART 1: 78 AUSTRALIAN VISAS WITH COMPLETE DATA
-- ============================================================================

DELETE FROM public.visas WHERE country = 'Australia';

INSERT INTO public.visas (
    subclass, name, country, category, is_active, cost_aud, processing_time_range, 
    duration, key_requirements, official_url, summary
) VALUES
-- WORK VISAS (20 visas)
('189', 'Skilled Independent', 'Australia', 'work', true, '$4,640', '8-12 months', 'Permanent', 
    'Points test 65+, Skills assessment, Competent English, Age under 45', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189',
    'Permanent visa for skilled workers not sponsored by employer, state, or family member'),
('190', 'Skilled Nominated', 'Australia', 'work', true, '$4,640', '8-12 months', 'Permanent', 
    'State/territory nomination, Points test 65+, Skills assessment, Competent English', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-nominated-190',
    'Permanent visa for skilled workers nominated by Australian state or territory'),
('491', 'Skilled Work Regional (Provisional)', 'Australia', 'work', true, '$4,640', '8-12 months', '5 years', 
    'State/family nomination, Regional work requirement, Points test 65+', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-work-regional-491',
    'Provisional visa for skilled workers to live and work in regional Australia'),
('482', 'Temporary Skill Shortage', 'Australia', 'work', true, '$1,455', '1-3 months', '2-4 years', 
    'Employer sponsorship, Skills assessment, 2 years experience, Labour market testing', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-skill-shortage-482',
    'Temporary visa for skilled workers sponsored by approved Australian employer'),
('186', 'Employer Nomination Scheme', 'Australia', 'work', true, '$4,640', '6-11 months', 'Permanent', 
    'Employer nomination, 3 years experience, Skills assessment, Under 45', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/employer-nomination-scheme-186',
    'Permanent visa for skilled workers nominated by Australian employer'),
('494', 'Skilled Employer Sponsored Regional', 'Australia', 'work', true, '$4,640', '6-9 months', '5 years', 
    'Regional employer sponsorship, Skills assessment, 3 years experience', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-employer-sponsored-regional-494',
    'Provisional visa for skilled workers sponsored by regional employer'),
('476', 'Skilled Recognised Graduate', 'Australia', 'work', true, '$465', '7-9 months', '18 months', 
    'Recent engineering degree from specified institutions, Under 31', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-recognised-graduate-476',
    'Temporary visa for recent engineering graduates to gain work experience'),
('887', 'Skilled Regional (Permanent)', 'Australia', 'work', true, '$425', '12-15 months', 'Permanent', 
    'Live in regional area 2+ years, Work 1+ year, Hold eligible provisional visa', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-regional-887',
    'Permanent visa pathway for provisional visa holders in regional Australia'),
('191', 'Skilled Regional (Permanent)', 'Australia', 'work', true, '$465', 'Not specified', 'Permanent', 
    'Hold 491/494 3+ years, Meet income requirement $53,900/year', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-regional-permanent-191',
    'Permanent residence for eligible provisional skilled regional visa holders'),
('407', 'Training', 'Australia', 'work', true, '$405', '4-6 months', '2 years', 
    'Nomination from approved organisation, Genuine training need, English proficiency', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/training-407',
    'Temporary visa for workplace-based occupational training'),
('408', 'Temporary Activity', 'Australia', 'work', true, '$310', '1-4 months', 'Up to 2 years', 
    'Specific activity: Entertainment, Research, Sport, Religious work', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-activity-408',
    'Temporary visa for special programs and activities'),
('403', 'Temporary Work (International Relations)', 'Australia', 'work', true, '$405', '1-4 months', 'Up to 4 years', 
    'Government agreement, Foreign government representative, Diplomatic privileges', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-work-international-relations-403',
    'Temporary visa for representatives of foreign governments'),
('400', 'Temporary Work (Short Stay Specialist)', 'Australia', 'work', true, '$405', '1-4 months', 'Up to 6 months', 
    'Highly specialised work, Non-ongoing role, Unique skills', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-work-short-stay-specialist-400',
    'Short-term visa for highly specialised, non-ongoing work'),
('858', 'Global Talent (Permanent)', 'Australia', 'work', true, '$4,110', '1-3 months', 'Permanent', 
    'High income threshold $167,500 OR Exceptional talent in target sector', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/global-talent-858',
    'Fast-track permanent visa for highly skilled professionals in priority sectors'),
('124', 'Distinguished Talent', 'Australia', 'work', true, '$4,110', '12-18 months', 'Permanent', 
    'Internationally recognised record of exceptional achievement in profession', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/distinguished-talent-124',
    'Permanent visa for individuals with internationally recognised exceptional talent'),
('188', 'Business Innovation and Investment (Provisional)', 'Australia', 'business', true, '$9,455', '12-24 months', '5 years', 
    'Business ownership OR Investment $2.5M+ OR $5M+ significant investor', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/business-innovation-and-investment-188',
    'Provisional visa for business owners, investors, and entrepreneurs'),
('888', 'Business Innovation and Investment (Permanent)', 'Australia', 'business', true, '$3,490', 'With 188 conditions', 'Permanent', 
    'Meet 188 stream requirements, Business/Investment activity, Residency requirements', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/business-innovation-and-investment-permanent-888',
    'Permanent residence for eligible Business Innovation and Investment visa holders'),
('444', 'Special Category (New Zealand Citizen)', 'Australia', 'work', true, 'Free', 'Instant', 'Indefinite', 
    'New Zealand citizen, Special category visa on arrival, Character requirements', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/special-category-444',
    'Special visa category for New Zealand citizens living in Australia'),
('416', 'Special Program', 'Australia', 'work', true, '$310', '1-3 months', 'Up to 1 year', 
    'Youth exchange, Cultural enrichment programs, Age 18-30', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/special-program-416',
    'Temporary visa for youth exchange and cultural programs'),
('422', 'Medical Practitioner', 'Australia', 'work', true, '$310', '1-3 months', 'Up to 4 years', 
    'Medical professionals, Doctors, Health workforce certificate', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/medical-practitioner-422',
    'Temporary visa for medical practitioners and healthcare professionals'),

-- FAMILY VISAS (18 visas)
('309', 'Partner (Provisional)', 'Australia', 'family', true, '$8,085', '12-18 months', '2 years', 
    'Genuine relationship, Sponsor is Australian PR/citizen, Health and character', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/partner-provisional-309',
    'Provisional visa for partners of Australian citizens or permanent residents'),
('100', 'Partner', 'Australia', 'family', true, '$1,435', 'With 309 grant', 'Permanent', 
    'Hold 309 for 2 years, Relationship continues, Live together', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/partner-100',
    'Permanent residence for provisional partner visa holders'),
('820', 'Partner (Temporary)', 'Australia', 'family', true, '$8,085', '12-18 months', '2 years', 
    'Genuine relationship, In Australia, Sponsor is Australian PR/citizen', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/partner-temporary-820',
    'Temporary onshore partner visa for those already in Australia'),
('801', 'Partner (Permanent)', 'Australia', 'family', true, '$1,435', 'With 820 grant', 'Permanent', 
    'Hold 820 for 2 years, Relationship continues, Meet requirements', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/partner-permanent-801',
    'Permanent residence for eligible temporary partner visa holders'),
('300', 'Prospective Marriage', 'Australia', 'family', true, '$8,085', '12-18 months', '9 months', 
    'Engaged to Australian, Met in person, Intent to marry within 9 months', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/prospective-marriage-300',
    'Temporary visa for fiancés of Australian citizens to marry in Australia'),
('101', 'Child', 'Australia', 'family', true, '$3,055', '12-18 months', 'Permanent', 
    'Parent is Australian PR/citizen, Under 18 or dependent, Single', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/child-101',
    'Permanent visa for children of Australian citizens or permanent residents'),
('802', 'Child (Onshore)', 'Australia', 'family', true, '$3,055', '12-18 months', 'Permanent', 
    'Parent is Australian PR/citizen, In Australia, Under 18 or dependent', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/child-onshore-802',
    'Permanent onshore visa for children in Australia'),
('143', 'Contributory Parent', 'Australia', 'family', true, '$47,755', '5-6 years', 'Permanent', 
    'Balance of family test, Assurance of support $10,000, Health check', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/contributory-parent-143',
    'Fast-track permanent parent visa with higher fees'),
('173', 'Contributory Parent (Temporary)', 'Australia', 'family', true, '$29,130', '2-4 years', '2 years', 
    'Temporary parent visa, Balance of family test, Can transition to 143', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/contributory-parent-temporary-173',
    'Temporary parent visa with pathway to permanent residence'),
('103', 'Parent', 'Australia', 'family', true, '$6,985', '30+ years', 'Permanent', 
    'Balance of family test, Assurance of support, Very long queue', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/parent-103',
    'Standard parent visa with very long processing times'),
('804', 'Aged Parent', 'Australia', 'family', true, '$4,225', '30+ years', 'Permanent', 
    'Pension age, Balance of family test, Long queue', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/aged-parent-804',
    'Onshore parent visa for applicants of pension age'),
('864', 'Contributory Aged Parent', 'Australia', 'family', true, '$47,755', '5-6 years', 'Permanent', 
    'Pension age, Fast track with higher fee, Assurance of support', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/contributory-aged-parent-864',
    'Fast-track permanent visa for aged parents'),
('884', 'Contributory Aged Parent (Temporary)', 'Australia', 'family', true, '$29,130', '2-4 years', '2 years', 
    'Temporary aged parent visa, Pension age requirement', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/contributory-aged-parent-temporary-884',
    'Temporary aged parent visa with permanent pathway'),
('836', 'Carer', 'Australia', 'family', true, '$2,055', '4-5 years', 'Permanent', 
    'Relative needs care, Willing to provide ongoing care, Medical evidence', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/carer-836',
    'Permanent visa for those who care for relatives with medical condition'),
('837', 'Orphan Relative', 'Australia', 'family', true, '$1,870', '12-18 months', 'Permanent', 
    'Under 18, Parent deceased, Australian relative, Unmarried', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/orphan-relative-837',
    'Permanent visa for orphaned relatives under 18'),
('117', 'Orphan Relative (Offshore)', 'Australia', 'family', true, '$1,870', '12-18 months', 'Permanent', 
    'Under 18, Outside Australia, Parent deceased, Australian relative', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/orphan-relative-offshore-117',
    'Offshore permanent visa for orphaned relatives'),
('115', 'Remaining Relative', 'Australia', 'family', true, '$4,350', '30+ years', 'Permanent', 
    'Remaining relative of Australian citizen/PR, No other close relatives', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/remaining-relative-115',
    'Permanent visa for those with no close relatives outside Australia'),
('870', 'Sponsored Parent (Temporary)', 'Australia', 'family', true, '$1,145', '3-6 months', '3-5 years', 
    'Parent of Australian citizen/PR, Sponsorship approval, Balance of family test waived', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/sponsored-parent-temporary-870',
    'Temporary parent visa allowing longer stays up to 5 years'),

-- STUDENT VISAS (5 visas)
('500', 'Student', 'Australia', 'student', true, '$710', '1-3 months', 'Course duration', 
    'Enrollment in CRICOS course, Financial capacity $21,041/year, English proficiency', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500',
    'Primary visa for international students to study in Australia'),
('485', 'Temporary Graduate', 'Australia', 'student', true, '$1,895', '2-4 months', '2-4 years', 
    'Recent Australian qualification, English proficiency, Apply within 6 months', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-graduate-485',
    'Work visa for recent graduates to gain Australian work experience'),
('590', 'Student Guardian', 'Australia', 'student', true, '$710', '1-3 months', 'Course duration', 
    'Guardian of student under 18, Financial capacity, Genuine temporary entrant', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-guardian-590',
    'Visa for parents or guardians accompanying students under 18'),
('407', 'Training', 'Australia', 'student', true, '$405', '4-6 months', '2 years', 
    'Nomination from approved organisation, Occupational training program', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/training-407',
    'Training visa for workplace-based occupational training'),
('476', 'Skilled Recognised Graduate', 'Australia', 'student', true, '$465', '7-9 months', '18 months', 
    'Engineering degree from specified institution, Under 31', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-recognised-graduate-476',
    'Work visa for recent engineering graduates'),

-- VISITOR VISAS (12 visas)
('600', 'Visitor', 'Australia', 'visitor', true, '$190', '20-30 days', '3-12 months', 
    'Genuine temporary visitor, Financial capacity, Strong ties to home country', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/visitor-600',
    'Tourist visa for holiday, visiting family, or short business visits'),
('601', 'Electronic Travel Authority', 'Australia', 'visitor', true, '$20', 'Instant', '12 months', 
    'Eligible passport, No criminal record, Business/tourism only', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/electronic-travel-authority-601',
    'Electronic visa for short-term business and tourism visits'),
('651', 'eVisitor', 'Australia', 'visitor', true, 'Free', 'Instant', '3 months', 
    'Eligible European passport, Genuine visitor, No work allowed', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/evisitor-651',
    'Free electronic visa for European passport holders'),
('417', 'Working Holiday', 'Australia', 'visitor', true, '$635', '1-2 weeks', '12 months', 
    'Age 18-30, Eligible passport, $5,000 funds, No dependent children', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/working-holiday-417',
    'Holiday and work visa for young people from eligible countries'),
('462', 'Work and Holiday', 'Australia', 'visitor', true, '$635', '1-2 weeks', '12 months', 
    'Age 18-30, Eligible passport, $5,000 funds, Limited spots per country', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-and-holiday-462',
    'Work and holiday visa for young people from partner countries'),
('679', 'Sponsored Family Visitor', 'Australia', 'visitor', true, '$145', '1-3 months', '12 months', 
    'Family sponsorship, Genuine visitor, Sponsor may provide bond', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/sponsored-family-visitor-679',
    'Visitor visa for those sponsored by Australian family members'),
('771', 'Transit', 'Australia', 'visitor', true, 'Free', 'Instant', '72 hours', 
    'Passing through Australia, Maximum 72 hours, Confirmed onward booking', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/transit-771',
    'Free transit visa for short stopovers'),
('988', 'Maritime Crew', 'Australia', 'visitor', true, 'Free', 'Instant', '30 days', 
    'Maritime crew, Sea-based work, Valid passport', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/maritime-crew-988',
    'Visa for crew members arriving by sea'),
('602', 'Medical Treatment', 'Australia', 'visitor', true, 'Free', 'Varies', 'Varies', 
    'Medical treatment in Australia, Adequate funds, Treatment arranged', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/medical-treatment-602',
    'Visa for medical treatment and consultations in Australia'),
('408', 'Temporary Activity', 'Australia', 'visitor', true, '$310', '1-4 months', 'Up to 2 years', 
    'Specific activities: Entertainment, Research, Sport, Special programs', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-activity-408',
    'Temporary visa for special activities and programs'),
('400', 'Temporary Work (Short Stay)', 'Australia', 'visitor', true, '$405', '1-4 months', 'Up to 6 months', 
    'Highly specialised work, Non-ongoing role, Unique skills', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-work-short-stay-specialist-400',
    'Short-term work visa for specialised, non-ongoing work'),
('461', 'New Zealand Citizen Family Relationship', 'Australia', 'visitor', true, '$425', '12-18 months', '5 years', 
    'Family member of NZ citizen (444 holder), Genuine relationship', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/new-zealand-citizen-family-relationship-461',
    'Temporary visa for family members of New Zealand citizens'),

-- OTHER/HUMANITARIAN VISAS (23 visas)
('010', 'Bridging A', 'Australia', 'other', true, 'Free', 'Automatic', 'Until decision', 
    'Applied for substantive visa in Australia, Automatic grant', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/bridging-a-010',
    'Temporary visa allowing lawful stay while substantive visa processes'),
('020', 'Bridging B', 'Australia', 'other', true, '$180', 'Varies', 'For travel', 
    'Hold Bridging A, Need to travel outside Australia', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/bridging-b-020',
    'Bridging visa with travel permission'),
('050', 'Bridging (General)', 'Australia', 'other', true, 'Free', 'Varies', 'Until decision', 
    'Unlawful non-citizen applying for visa, Last resort', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/bridging-general-050',
    'Bridging visa for those who become unlawful'),
('051', 'Bridging (Protection Visa Applicant)', 'Australia', 'humanitarian', true, 'Free', 'Varies', 'Until decision', 
    'Applying for protection visa, Automatic grant', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/bridging-protection-visa-applicant-051',
    'Bridging visa for protection visa applicants'),
('785', 'Temporary Protection', 'Australia', 'humanitarian', true, 'Free', 'Varies', '3 years', 
    'Temporary protection status, Cannot apply for permanent', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-protection-785',
    'Temporary visa for those who arrived by boat before 2014'),
('790', 'Safe Haven Enterprise', 'Australia', 'humanitarian', true, 'Free', 'Varies', '5 years', 
    'Work and study in regional Australia, Pathway to permanent', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/safe-haven-enterprise-790',
    'Visa for refugees willing to work in regional Australia'),
('866', 'Protection', 'Australia', 'humanitarian', true, '$40', 'Varies', 'Permanent', 
    'Protection visa for refugees, Well-founded fear of persecution', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/protection-866',
    'Permanent visa for refugees meeting protection criteria'),
('201', 'In-country Special Humanitarian', 'Australia', 'humanitarian', true, '$40', 'Varies', 'Permanent', 
    'Compelling humanitarian circumstances, In home country', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/in-country-special-humanitarian-201',
    'Permanent visa for those in compelling humanitarian situations'),
('202', 'Global Special Humanitarian', 'Australia', 'humanitarian', true, '$40', 'Varies', 'Permanent', 
    'Proposer in Australia, Compelling reasons, Outside Australia', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/global-special-humanitarian-202',
    'Permanent visa for those outside Australia with compelling circumstances'),
('203', 'Emergency Rescue', 'Australia', 'humanitarian', true, '$40', 'Priority', 'Permanent', 
    'Urgent and compelling humanitarian circumstances, Immediate danger', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/emergency-rescue-203',
    'Priority permanent visa for urgent humanitarian cases'),
('204', 'Woman at Risk', 'Australia', 'humanitarian', true, '$40', 'Priority', 'Permanent', 
    'Woman without male protection, Compelling circumstances, In danger', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/woman-at-risk-204',
    'Priority visa for vulnerable women in dangerous situations'),
('155', 'Resident Return (5 years)', 'Australia', 'other', true, '$425', '1-3 weeks', '5 years', 
    'Permanent resident returning, Meet residence requirement (2 years in 5)', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/resident-return-155',
    'Travel facility for permanent residents returning to Australia'),
('157', 'Resident Return (3 months)', 'Australia', 'other', true, '$425', '1-3 weeks', '3 months', 
    'Permanent resident, Compelling reasons for absence', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/resident-return-157',
    'Short-term travel facility for permanent residents'),
('151', 'Citizen (by descent)', 'Australia', 'other', true, '$345', '3-6 months', 'Citizenship', 
    'Born overseas to Australian parent, Parent was citizen at time of birth', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/citizen-by-descent-151',
    'Evidence of Australian citizenship for those born overseas'),
('445', 'Dependent Child', 'Australia', 'family', true, '$2,935', 'Varies', 'Temporary', 
    'Dependent child of temporary visa holder, Under 18 or dependent', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/dependent-child-445',
    'Temporary visa for dependent children of temporary visa holders'),
('957', 'New Zealand Citizen Family Relationship (Temporary)', 'Australia', 'family', true, '$425', 'Varies', '2 years', 
    'Temporary family member of NZ citizen, Genuine relationship', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/new-zealand-citizen-family-relationship-temporary-957',
    'Temporary visa for family of NZ citizens'),
('942', 'Sponsored Parent (Temporary)', 'Australia', 'family', true, '$1,145', '3-6 months', '3-5 years', 
    'Parent of Australian citizen/PR, Sponsorship approval', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/sponsored-parent-temporary-942',
    'Temporary parent visa for longer stays'),
('126', 'Domestic Worker - Diplomat', 'Australia', 'work', true, 'Variable', '2-4 weeks', 'Up to 5 years', 
    'Diplomat household staff, Diplomatic passport, Employment contract', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/domestic-worker-diplomat-126',
    'Visa for domestic workers of diplomats'),
('411', 'Exchange', 'Australia', 'work', true, '$310', '1-4 months', 'Up to 2 years', 
    'Exchange programs, Approved organisation, Cultural exchange', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/exchange-411',
    'Temporary visa for exchange programs'),
('415', 'Foreign Government Agency', 'Australia', 'work', true, '$310', '1-3 months', 'Up to 4 years', 
    'Foreign government workers, Official duties, Government agreement', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/foreign-government-agency-415',
    'Visa for foreign government agency staff'),
('418', 'Educational', 'Australia', 'work', true, '$310', '1-3 months', 'Up to 2 years', 
    'Teachers and educators, Approved educational institution', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/educational-418',
    'Temporary visa for teachers and educators'),
('420', 'Temporary Work (Religious)', 'Australia', 'work', true, '$310', '1-3 months', 'Up to 2 years', 
    'Religious workers, Sponsoring religious organisation, Full-time religious work', 
    'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-work-religious-420',
    'Temporary visa for full-time religious workers')
ON CONFLICT (subclass) DO NOTHING;

SELECT '✓ Part 1: 78 visas inserted' as status, COUNT(*)::text as count FROM public.visas;
